export const ADD_TO_CART = 'ADD_TO_CART'
export const ADD_TO_CART_SUCCESS = 'ADD_TO_CART_SUCCESS'
export const ADD_TO_CART_FAIL = 'ADD_TO_CART_FAIL'

export const ADD_ORDER = 'ADD_ORDER'
export const ADD_ORDER_SUCCESS = 'ADD_ORDER_SUCCESS'
export const ADD_ORDER_FAIL = 'ADD_ORDER_FAIL'

export const ORDER_CHANGE_STATE = 'ORDER_CHANGE_STATE'
export const ORDER_CHANGE_STATE_SUCCESS = 'ORDER_CHANGE_STATE_SUCCESS'
export const ORDER_CHANGE_STATE_FAIL = 'ORDER_CHANGE_STATE_FAIL'

export const GET_ALL_PAYMENT = 'GET_ALL_PAYMENT'
export const GET_ALL_PAYMENT_SUCCESS = 'GET_ALL_PAYMENT_SUCCESS'
export const GET_ALL_PAYMENT_FAIL = 'GET_ALL_PAYMENT_FAIL'

export const GET_ALL_SHIPMENT = 'GET_ALL_SHIPMENT'
export const GET_ALL_SHIPMENT_SUCCESS = 'GET_ALL_SHIPMENT_SUCCESS'
export const GET_ALL_SHIPMENT_FAIL = 'GET_ALL_SHIPMENT_FAIL'
