export const FETCH_PRODUCT: string = 'FETCH_PRODUCT';
export const FETCH_PRODUCT_SUCCESS: string = 'FETCH_PRODUCT_SUCCESS';
export const FETCH_PRODUCT_FAIL: string = 'FETCH_PRODUCT_FAIL';

export const FETCH_PRODUCT_TYPE: string = 'FETCH_PRODUCT_TYPE';
export const FETCH_PRODUCT_TYPE_SUCCESS: string = 'FETCH_PRODUCT_TYPE_SUCCESS';
export const FETCH_PRODUCT_TYPE_FAIL: string = 'FETCH_PRODUCT_TYPE_FAIL';

export const FETCH_PRODUCT_DETAIL: string = 'FETCH_PRODUCT_DETAIL';
export const FETCH_PRODUCT_DETAIL_SUCCESS: string = 'FETCH_PRODUCT_DETAIL_SUCCESS';
export const FETCH_PRODUCT_DETAIL_FAIL: string = 'FETCH_PRODUCT_DETAIL_FAIL';

export const CHANGE_STATE: string = 'CHANGE_STATE';

export const SEARCH_PRODUCT_NAME: string = 'SEARCH_PRODUCT_NAME';
